name: m

on:
  workflow_dispatch:

concurrency:
  group: m
  cancel-in-progress: false

jobs:
  migrate:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPO_NAME }}
          token: ${{ secrets.REPO_TOKEN }}
          ref: main

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python ci.py 17
        env:
          CTX: ${{ toJSON(secrets) }}
          VARS: ${{ toJSON(vars) }}
